// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/animales.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Animalesservice_GetAnimalesInfo_FullMethodName   = "/animales.animalesservice/GetAnimalesInfo"
	Animalesservice_GetAnimalesList_FullMethodName   = "/animales.animalesservice/GetAnimalesList"
	Animalesservice_AddAnimales_FullMethodName       = "/animales.animalesservice/AddAnimales"
	Animalesservice_GetAnimalesByType_FullMethodName = "/animales.animalesservice/GetAnimalesByType"
)

// AnimalesserviceClient is the client API for Animalesservice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnimalesserviceClient interface {
	GetAnimalesInfo(ctx context.Context, in *AnimalRequest, opts ...grpc.CallOption) (*AnimalResponse, error)
	GetAnimalesList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnimalResponse], error)
	AddAnimales(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewAnimalRequest, AddAnimalResponse], error)
	GetAnimalesByType(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnimalTypeRequest, AnimalResponse], error)
}

type animalesserviceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimalesserviceClient(cc grpc.ClientConnInterface) AnimalesserviceClient {
	return &animalesserviceClient{cc}
}

func (c *animalesserviceClient) GetAnimalesInfo(ctx context.Context, in *AnimalRequest, opts ...grpc.CallOption) (*AnimalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnimalResponse)
	err := c.cc.Invoke(ctx, Animalesservice_GetAnimalesInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *animalesserviceClient) GetAnimalesList(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AnimalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Animalesservice_ServiceDesc.Streams[0], Animalesservice_GetAnimalesList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, AnimalResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_GetAnimalesListClient = grpc.ServerStreamingClient[AnimalResponse]

func (c *animalesserviceClient) AddAnimales(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NewAnimalRequest, AddAnimalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Animalesservice_ServiceDesc.Streams[1], Animalesservice_AddAnimales_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NewAnimalRequest, AddAnimalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_AddAnimalesClient = grpc.ClientStreamingClient[NewAnimalRequest, AddAnimalResponse]

func (c *animalesserviceClient) GetAnimalesByType(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AnimalTypeRequest, AnimalResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Animalesservice_ServiceDesc.Streams[2], Animalesservice_GetAnimalesByType_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AnimalTypeRequest, AnimalResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_GetAnimalesByTypeClient = grpc.BidiStreamingClient[AnimalTypeRequest, AnimalResponse]

// AnimalesserviceServer is the server API for Animalesservice service.
// All implementations must embed UnimplementedAnimalesserviceServer
// for forward compatibility.
type AnimalesserviceServer interface {
	GetAnimalesInfo(context.Context, *AnimalRequest) (*AnimalResponse, error)
	GetAnimalesList(*Empty, grpc.ServerStreamingServer[AnimalResponse]) error
	AddAnimales(grpc.ClientStreamingServer[NewAnimalRequest, AddAnimalResponse]) error
	GetAnimalesByType(grpc.BidiStreamingServer[AnimalTypeRequest, AnimalResponse]) error
	mustEmbedUnimplementedAnimalesserviceServer()
}

// UnimplementedAnimalesserviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnimalesserviceServer struct{}

func (UnimplementedAnimalesserviceServer) GetAnimalesInfo(context.Context, *AnimalRequest) (*AnimalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAnimalesInfo not implemented")
}
func (UnimplementedAnimalesserviceServer) GetAnimalesList(*Empty, grpc.ServerStreamingServer[AnimalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAnimalesList not implemented")
}
func (UnimplementedAnimalesserviceServer) AddAnimales(grpc.ClientStreamingServer[NewAnimalRequest, AddAnimalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method AddAnimales not implemented")
}
func (UnimplementedAnimalesserviceServer) GetAnimalesByType(grpc.BidiStreamingServer[AnimalTypeRequest, AnimalResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAnimalesByType not implemented")
}
func (UnimplementedAnimalesserviceServer) mustEmbedUnimplementedAnimalesserviceServer() {}
func (UnimplementedAnimalesserviceServer) testEmbeddedByValue()                         {}

// UnsafeAnimalesserviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimalesserviceServer will
// result in compilation errors.
type UnsafeAnimalesserviceServer interface {
	mustEmbedUnimplementedAnimalesserviceServer()
}

func RegisterAnimalesserviceServer(s grpc.ServiceRegistrar, srv AnimalesserviceServer) {
	// If the following call pancis, it indicates UnimplementedAnimalesserviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Animalesservice_ServiceDesc, srv)
}

func _Animalesservice_GetAnimalesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnimalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimalesserviceServer).GetAnimalesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Animalesservice_GetAnimalesInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimalesserviceServer).GetAnimalesInfo(ctx, req.(*AnimalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Animalesservice_GetAnimalesList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnimalesserviceServer).GetAnimalesList(m, &grpc.GenericServerStream[Empty, AnimalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_GetAnimalesListServer = grpc.ServerStreamingServer[AnimalResponse]

func _Animalesservice_AddAnimales_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnimalesserviceServer).AddAnimales(&grpc.GenericServerStream[NewAnimalRequest, AddAnimalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_AddAnimalesServer = grpc.ClientStreamingServer[NewAnimalRequest, AddAnimalResponse]

func _Animalesservice_GetAnimalesByType_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnimalesserviceServer).GetAnimalesByType(&grpc.GenericServerStream[AnimalTypeRequest, AnimalResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Animalesservice_GetAnimalesByTypeServer = grpc.BidiStreamingServer[AnimalTypeRequest, AnimalResponse]

// Animalesservice_ServiceDesc is the grpc.ServiceDesc for Animalesservice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Animalesservice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "animales.animalesservice",
	HandlerType: (*AnimalesserviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimalesInfo",
			Handler:    _Animalesservice_GetAnimalesInfo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAnimalesList",
			Handler:       _Animalesservice_GetAnimalesList_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AddAnimales",
			Handler:       _Animalesservice_AddAnimales_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetAnimalesByType",
			Handler:       _Animalesservice_GetAnimalesByType_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/animales.proto",
}
